Controllers/CarController.cs
using ASP.NET_Projekt_Wypozyczalnia.Models;
using ASP.NET_Projekt_Wypozyczalnia.Services;
using ASP.NET_Projekt_Wypozyczalnia.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ASP.NET_Projekt_Wypozyczalnia.Controllers
{
    [Authorize]
    public class CarController : Controller
    {
        private readonly ICarService _carService;

        public CarController(ICarService carService)
        {
            _carService = carService;
        }

        // GET Odczyt
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allCars = await _carService.GetAllCarsAsync();

            var fullViewModels = allCars.Select(car => new CarViewModel
            {
                CarID = car.CarID,
                Make = car.Make,
                Model = car.Model,
                Year = car.Year,
                RegistrationNumber = car.RegistrationNumber,
                CarStatus = car.CarStatus,
                Mileage = car.Mileage,
                InspectionDate = car.InspectionDate,
                InsuranceDate = car.InsuranceDate,
                EngineCapacity = car.EngineCapacity,
                FuelType = car.FuelType
            }).ToList();

            var publicViewModels = allCars.Select(car => new CarPublicViewModel
            {
                Make = car.Make,
                Model = car.Model,
                Year = car.Year,
                CarStatus = car.CarStatus,
                FuelType = car.FuelType,
                Mileage = car.Mileage
            }).ToList();

            var viewModel = new CarIndexViewModel
            {
                AllCars = fullViewModels,
                PublicCars = publicViewModels
            };

            return View(viewModel);
        }


        // GET Tworzenie
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST Tworzenie
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("CarID,Make,Model,Year,RegistrationNumber,CarStatus,Mileage,InspectionDate,InsuranceDate,EngineCapacity,FuelType")] Car car)
        {
            if (ModelState.IsValid)
            {
                //if (car.ImageFile != null && car.ImageFile.Length > 0)
                //{
                //    var fileName = Path.GetFileName(car.ImageFile.FileName);
                //    var filePath = Path.Combine("wwwroot/images", fileName);

                //    using var stream = new FileStream(filePath, FileMode.Create);
                //    await car.ImageFile.CopyToAsync(stream);

                //    car.ImagePath = "/images/" + fileName;
                //}
                await _carService.AddCarAsync(car);
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET Edycja
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _carService.GetCarByIdAsync(id.Value);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST Edycja
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> Edit(int id, [Bind("CarID,Make,Model,Year,RegistrationNumber,CarStatus,Mileage,InspectionDate,InsuranceDate,EngineCapacity,FuelType,CarPicture")] Car car)
        {
            if (id != car.CarID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _carService.UpdateCarAsync(car);
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET Usuwanie
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _carService.GetCarByIdAsync(id.Value);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST Usuwanie
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _carService.DeleteCarAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/ClientController.cs
using ASP.NET_Projekt_Wypozyczalnia.Data;
using ASP.NET_Projekt_Wypozyczalnia.Models;
using ASP.NET_Projekt_Wypozyczalnia.Services;
using ASP.NET_Projekt_Wypozyczalnia.Validators;
using ASP.NET_Projekt_Wypozyczalnia.ViewModels;

using FluentValidation;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using Microsoft.AspNetCore.Mvc.Localization;

namespace ASP.NET_Projekt_Wypozyczalnia.Controllers
{
    [Authorize]
    public class ClientController : Controller
    {
        private readonly IClientService _clientService;
        private readonly IValidator<Client> _clientValidator;
        private readonly ApplicationDbContext _context;
        //private readonly IStringLocalizer<SharedResource> _localizer;

        public ClientController(IClientService clientService, IValidator<Client> clientValidator, ApplicationDbContext context)
        {
            _clientService = clientService;
            _clientValidator = clientValidator;
            _context = context;
        }
        //GET z paginacją
        [AllowAnonymous]
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> Index(int pageNumber = 1, int pageSize = 10)
        {
            if (pageNumber < 1)
            {
                pageNumber = 1;
            }

            var (clients, totalCount) = await _clientService.GetAllClientsAsync(pageNumber, pageSize);

            //var viewModels = clients.Select(ClientViewModel.FromClient).ToList();
            var viewModels = clients.Adapt<List<ClientViewModel>>();

            var model = new ClientListViewModel
            {
                Clients = viewModels,
                PageNumber = pageNumber,
                PageSize = pageSize,
                TotalCount = totalCount
            };

            return View(model);
        }
        //GET
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View(new Client());
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(Client client)
        {

            var validationResult = await _clientValidator.ValidateAsync(client);

            if (!validationResult.IsValid)
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
                return View(client);
            }

            await _clientService.AddClientAsync(client);
            return RedirectToAction(nameof(Index));
        }
        //GET
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var client = await _clientService.GetClientByIdAsync(id.Value);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> Edit(int id, [Bind("ClientID,FirstName,LastName,Email,PhoneNumber,DocumentNumber,DocumentType,Address")] Client client)
        {
            if (id != client.ClientID)
            {
                return NotFound();
            }
    

            var validationResult = await _clientValidator.ValidateAsync(client);
    
            if (!validationResult.IsValid)
            {
                foreach (var error in validationResult.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
                return View(client);
            }

            await _clientService.UpdateClientAsync(client);
            return RedirectToAction(nameof(Index));
        }
        //GET
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var client = await _clientService.GetClientByIdAsync(id.Value);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _clientService.DeleteClientAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/RentalItemsController.cs
using Microsoft.AspNetCore.Mvc;
using ASP.NET_Projekt_Wypozyczalnia.Models;
using ASP.NET_Projekt_Wypozyczalnia.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace ASP.NET_Projekt_Wypozyczalnia.Controllers
{
    [Authorize]
    public class RentalItemsController : Controller
    {
        private readonly IRentalItemsService _rentalItemsservice;
        private readonly ICarService _carService;
        private readonly IClientService _clientService;

        public RentalItemsController(
            IRentalItemsService rentalItemsService,
            IClientService clientService,
            ICarService carService)
        {
            _clientService = clientService;
            _carService = carService;
            _rentalItemsservice = rentalItemsService;
        }

        // GET: List
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> Index()
        {
            var rentalItems = await _rentalItemsservice.GetAllRentalItemsAsync();
            return View(rentalItems);
        }

        // GET: Create
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> Create(int pageNumber = 1, int pageSize = 10)
        {
            if (pageNumber < 1) pageNumber = 1;

            var (clients, _) = await _clientService.GetAllClientsAsync(pageNumber, pageSize);
            ViewBag.ClientID = new SelectList(clients, "ClientID", "FirstName");
            ViewBag.CarID = new SelectList(await _carService.GetAllCarsAsync(), "CarID", "Make");

            return View();
        }

        // POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> Create([Bind("RentalID,ClientID,CarID,RentalDate,ReturnDate,ExpectedReturnDate,RentalStatus")] RentalItems rentalItem)
        {
            if (ModelState.IsValid)
            {
                await _rentalItemsservice.AddRentalItemAsync(rentalItem);
                return RedirectToAction(nameof(Index));
            }

            var (clients, _) = await _clientService.GetAllClientsAsync(1, 10);
            ViewBag.ClientID = new SelectList(clients, "ClientID", "FirstName", rentalItem.ClientID);
            ViewBag.CarID = new SelectList(await _carService.GetAllCarsAsync(), "CarID", "Make", rentalItem.CarID);

            return View(rentalItem);
        }

        // GET: Edit
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> Edit(int id)
        {
            if (id <= 0) return NotFound();

            var rentalItem = await _rentalItemsservice.GetRentalItemByIdAsync(id);
            if (rentalItem == null) return NotFound();

            var (clients, _) = await _clientService.GetAllClientsAsync(1, 10);
            ViewBag.ClientID = new SelectList(clients, "ClientID", "FirstName", rentalItem.ClientID);
            ViewBag.CarID = new SelectList(await _carService.GetAllCarsAsync(), "CarID", "Make", rentalItem.CarID);

            return View(rentalItem);
        }

        // POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Manager")]
        public async Task<IActionResult> Edit(int id, [Bind("RentalID,ClientID,CarID,RentalDate,ReturnDate,ExpectedReturnDate,RentalStatus")] RentalItems rentalItem)
        {
            if (id != rentalItem.RentalID) return NotFound();

            if (ModelState.IsValid)
            {
                await _rentalItemsservice.UpdateRentalItemAsync(rentalItem);
                return RedirectToAction(nameof(Index));
            }

            var (clients, _) = await _clientService.GetAllClientsAsync(1, 10);
            ViewBag.ClientID = new SelectList(clients, "ClientID", "FirstName", rentalItem.ClientID);
            ViewBag.CarID = new SelectList(await _carService.GetAllCarsAsync(), "CarID", "Make", rentalItem.CarID);

            return View(rentalItem);
        }

        // GET: Delete
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return NotFound();

            var rentalItem = await _rentalItemsservice.GetRentalItemByIdAsync(id);
            if (rentalItem == null) return NotFound();

            return View(rentalItem);
        }

        // POST: Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _rentalItemsservice.DeleteRentalItemAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="pl">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Panel administratora</title>

    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet" />
</head>

<body id="page-top">
    <div id="wrapper">

        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Admin" asp-action="Dashboard">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin</div>
            </a>

            <hr class="sidebar-divider my-0" />

            <li class="nav-item">
                <a class="nav-link" asp-controller="Admin" asp-action="Dashboard">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <hr class="sidebar-divider" />

            @if (User.IsInRole("Admin") || User.IsInRole("Manager"))
            {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Car" asp-action="Index">
                        <i class="fas fa-car"></i>
                        <span>Samochody</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Client" asp-action="Index">
                        <i class="fas fa-users"></i>
                        <span>Klienci</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="RentalItems" asp-action="Index">
                        <i class="fas fa-handshake"></i>
                        <span>Wypożyczenia</span>
                    </a>
                </li>
            }

            <hr class="sidebar-divider d-none d-md-block" />
        </ul>
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    @{
                        var currentCulture = Context.Request.Query["culture"].ToString() ?? "pl";
                        var cultures = new Dictionary<string, string>
                                            {
                                            { "pl", "🇵🇱 Polski" },
                                            { "en", "🇬🇧 English" },
                                            { "de", "🇩🇪 Deutsch" }
                                            };
                    }

                    <form method="get" class="d-inline-block ms-3">
                        <input type="hidden" name="returnUrl" value="@Context.Request.Path" />
                        <select name="culture" class="form-select form-select-sm" onchange="this.form.submit()" style="width: auto; display: inline;">
                            @foreach (var culture in cultures)
                            {
                                <option value="@culture.Key" selected="@(culture.Key == currentCulture ? "selected" : null)">
                                    @culture.Value
                                </option>
                            }
                        </select>
                    </form>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">
                                    @User.Identity?.Name
                                </span>
                                <i class="fas fa-user-circle fa-lg"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <form asp-area="Identity" asp-page="/Account/Logout" method="post" class="dropdown-item">
                                    <button type="submit" class="btn btn-link text-left w-100 p-0">
                                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                        Wyloguj
                                    </button>
                                </form>
                            </div>
                        </li>
                    </ul>
                </nav>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>

            <footer class="sticky-footer bg-white mt-4">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; ASP.NET Wypożyczalnia 2025</span>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/js/sb-admin-2.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Authorization
@using Microsoft.AspNetCore.Mvc.Razor
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NET_Projekt_Wypozyczalnia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/sbadmin/css/sb-admin-2.min.css" rel="stylesheet" />
    <link href="~/sbadmin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NET_Projekt_Wypozyczalnia.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark shadow-sm mb-4">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Wypożyczalnia</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Car" asp-action="Index">@Localizer["Cars"]</a>
                        </li>
                        @if (User.IsInRole("Manager") || User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Client" asp-action="Index">@Localizer["Clients"]</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="RentalItems" asp-action="Index">@Localizer["Rentals"]</a>
                            </li>
                        }
                    </ul>

                    <ul class="navbar-nav ms-auto d-flex flex-row gap-2 align-items-center">
                        @{
                            var currentCulture = Context.Request.Query["culture"].ToString() ?? "pl";
                            var cultures = new Dictionary<string, string>
                                                {
                                                { "pl", "🇵🇱 Polski" },
                                                { "en", "🇬🇧 English" },
                                                { "de", "🇩🇪 Deutsch" }
                                                };
                        }

                        <form method="get" class="d-inline-block ms-3">
                            <input type="hidden" name="returnUrl" value="@Context.Request.Path" />
                            <select name="culture" class="form-select form-select-sm" onchange="this.form.submit()" style="width: auto; display: inline;">
                                @foreach (var culture in cultures)
                                {
                                    <option value="@culture.Key" selected="@(culture.Key == currentCulture ? "selected" : null)">
                                        @culture.Value
                                    </option>
                                }
                            </select>
                        </form>

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Home" asp-action="Dashboard">
                                    <i class="fas fa-fw fa-tachometer-alt"></i>
                                    <span>@Localizer["Dashboard"]</span>
                                </a>
                            </li>
                        }

                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item text-white">@Localizer["Welcome"], @UserManager.GetUserName(User)!</li>
                            <li>
                                <form asp-area="Identity" asp-page="/Account/Logout" method="post">
                                    <button type="submit" class="btn btn-outline-light btn-sm">@Localizer["Logout"]</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li><a class="btn btn-outline-light btn-sm" asp-area="Identity" asp-page="/Account/Login">@Localizer["Login"]</a></li>
                            <li><a class="btn btn-light btn-sm" asp-area="Identity" asp-page="/Account/Register">@Localizer["Register"]</a></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ASP.NET_Projekt_Wypożyczalnia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>